version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: recipes_db
    ports:
      - "3306:3306"
    volumes:
      - b06ca13d2a381e78447cfb18d80e97dd747aced003215ca1562a26c75ece6937:/var/lib/mysql

volumes:
  b06ca13d2a381e78447cfb18d80e97dd747aced003215ca1562a26c75ece6937:
    external: true
